### ISSUE TITLE
Extended vs Perl regular expressions in episode 2

### ISSUE THREAD

**Issue by mawds** [data-lessons/library-shell-DEPRECATED#80]
In episode 2, some of the exercises use extended (`-E`) regular expressions.   As far as I can tell, Perl compatible regular expressions (`-P`) are more powerful (see, e.g. https://www.regular-expressions.info/posix.html).

Is there any reason for using `-E` rather than `-P`?

Extended regular expressions don't support `\d` to match digits (tested on GNU grep 3.1) so the first solution to "Searching with regular expressions" is incorrect, and won't match anything. To use an extended regular expression you need:
```
grep -oE '[0-9]{4}-[0-9]{4}' 2014-01_JA.tsv
```

Rather than introduce ranges, it might be easier to only use Perl compatible regular expressions in the episode.  I'm happy to write a pull request to do this if you agree with the approach.

**Comment by danmichaelo** [comment]
Probably because `-P` is not available in BSD grep (as found on e.g. Macs). And funnily enough, BSD grep *does* support `\d` with `-E`.. so the best cross-platform solution is probably ranges. Or keep the two solutions, but explain better.

In any case, the exercise requires knowledge of something that hasn't been teached (`\d` or `[0-9]`) afaics, so I wonder if it would be good to provide a hint.

**Comment by weaverbel** [comment]
@mawds We don't go into Perl at all, and I don't see us going there either so I would rather use terms that are comptaible with the shell, which we are teaching.

**Comment by mawds** [comment]
Thanks @danmichaelo . I didn't  realise it was so different on the Mac!   

Character classes are already covered.  Extending this to include ranges might be a way of covering the material needed for the exercise?  Let me know if you'd like me to submit a PR doing this.
